### ISSUE TITLE
細かい修正

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/tsugunai#2]
daigo	[10:45 AM]  
移動の時の

[10:45]  
マーカーでてないー

[10:45]  
画像せっかくあげたのに。

hajimehoshi	[10:45 AM]  
未実装

daigo	[10:46 AM]  
移動おそいな

hajimehoshi	[10:46 AM]  
はやくできるよ

daigo	[10:46 AM]  
最後に彼女は〜　準拠にしよう

hajimehoshi	[10:46 AM]  
歩行がちゃんとできているか確認するために若干遅くしてた

daigo	[10:47 AM]  
机のよこのタイルは

[10:47]  
通行可能にしよう！

hajimehoshi	[10:47 AM]  
はいはい

daigo	[10:47 AM]  
ソファのまえも通り抜けたい

**Comment by hajimehoshi** [comment]
[ ] マーカーでてないー
[*] 移動おそいな
[ ] 机のよこのタイルは通行可能にしよう
[ ] ソファのまえも通り抜けたい

**Comment by hajimehoshi** [comment]
Done all but the marker.

**Comment by hajimehoshi** [comment]
All done.
